### PR TITLE
Adding some functional tests

### PR DESCRIPTION
**Pull request by gmacgilchrist**
This PR adds some additional functional tests to provide answers for default calculations using different `lambda` values, as well as using different methods within the calculation of `.G`.

This partially addresses #10.

### CODE REVIEW

**Comment by jkrasting** [comment]
@gmacgilchrist - interesting. These tests failed on the CI, but they did work for me.  Curious - what platform did you develop them on?

**Comment by jkrasting** [comment]
Nevermind @gmacgilchrist -- #29 should fix this issue

**Comment by jetesdal** [comment]
Thanks @jkrasting for looking into this. Is the test still failing or do we have to re-run the test to check if it is fixed now that #29 has been merged?

**Comment by jkrasting** [comment]
I rebased @gmacgilchrist's PR just now and submitted #30.

**Pull request closed without merging**
